import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { Finding, ScanResult } from './types.js';

export function escapeHtml(input: string): string {
  return input.replace(/[&<>"']/g, char => {
    const replacements: Record<string, string> = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#39;'
    };
    return replacements[char];
  });
}

function renderFinding(finding: Finding): string {
  const label = escapeHtml(finding.severity.toUpperCase());
  // Screenshot links are local filenames generated by our scanner, never arbitrary URLs.
  const claimedPath = finding.evidence?.screenshot;
  const screenshotPath = claimedPath && /^screenshots\/(?:[a-f0-9]{12}-)?[0-9]{3,4}x[0-9]{3,4}\.png$/.test(claimedPath)
    ? claimedPath
    : undefined;
  const image = screenshotPath
    ? '<a href="' + escapeHtml(screenshotPath) +
      '"><img loading="lazy" src="' + escapeHtml(screenshotPath) +
      '" alt="Screenshot for ' + escapeHtml(finding.title) + '"></a>'
    : '';
  const candidates = finding.evidence?.candidates?.length
    ? '<details><summary>Possible overflow elements (' + finding.evidence.candidates.length +
      ')</summary><ol>' + finding.evidence.candidates.map(candidate =>
        '<li><code>' + escapeHtml(candidate.selector) + '</code> (' +
        candidate.overflowPx + 'px beyond viewport)</li>'
      ).join('') + '</ol></details>'
    : '';
  return '<article class="issue">' +
    '<div class="issue-head"><span class="pill ' + finding.severity + '">' + label +
    '</span><span class="muted">' + finding.viewport.width + ' × ' +
    finding.viewport.height + '</span></div>' +
    '<h3>' + escapeHtml(finding.title) + '</h3>' +
    '<p>' + escapeHtml(finding.description) + '</p>' +
    (finding.pageUrl ? '<p class="muted">Page: <code>' +
      escapeHtml(finding.pageUrl) + '</code></p>' : '') +
    '<p class="muted"><code>' + escapeHtml(finding.ruleId) + '</code> · ' +
    escapeHtml(finding.confidence) + '</p>' +
    (finding.selector ? '<p class="selector">Element: <code>' +
      escapeHtml(finding.selector) + '</code></p>' : '') +
    (finding.evidence?.detail ? '<p class="muted">' +
      escapeHtml(finding.evidence.detail) + '</p>' : '') +
    candidates + image + '</article>';
}

export function renderHtmlReport(result: ScanResult): string {
  const high = result.findings.filter(f => f.severity === 'high').length;
  const medium = result.findings.filter(f => f.severity === 'medium').length;
  const low = result.findings.filter(f => f.severity === 'low').length;
  const issues = result.findings.length
    ? [...result.findings].sort((a, b) => {
        const rank = { high: 3, medium: 2, low: 1 };
        return rank[b.severity] - rank[a.severity];
      }).map(renderFinding).join('\n')
    : '<div class="empty">No issues found by the enabled rules. This is not a guarantee that the site has no bugs.</div>';
  const css = [
    ':root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,sans-serif;background:#080e1b;color:#f3f6fc}',
    '*{box-sizing:border-box}body{margin:0;line-height:1.6}',
    'main{max-width:1120px;margin:auto;padding:40px 24px 90px}',
    '.brand{font-weight:850;letter-spacing:-.03em;color:#84edd5;font-size:19px}',
    'h1{font-size:clamp(32px,5vw,60px);letter-spacing:-.05em;line-height:1.1;margin:25px 0 10px}',
    'h2{margin-top:55px;font-size:24px}h3{margin:14px 0 8px;font-size:20px}',
    '.muted{color:#99a9c4;font-size:14px}.subtitle{color:#afbdd3;font-size:17px}',
    '.stats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:30px}',
    '.stat{background:#111c2e;border:1px solid #26344a;border-radius:16px;padding:20px}',
    '.stat b{font-size:32px;display:block}.stat span{color:#a5b4cb}',
    '.issue{background:#101b2d;border:1px solid #26364c;border-radius:18px;padding:24px;margin:15px 0;overflow-wrap:anywhere}',
    '.issue-head{display:flex;align-items:center;gap:13px}.pill{padding:4px 10px;border-radius:30px;font-size:11px;font-weight:800;letter-spacing:.06em}',
    '.high{color:#ffc0c0;background:#5a2832}.medium{color:#ffe3a1;background:#5c4725}.low{color:#b4e7fc;background:#24495a}',
    'code{color:#b7dfd8}.selector{font-size:14px}',
    'img{display:block;max-width:100%;width:650px;border-radius:12px;border:1px solid #334862;margin-top:20px}',
    'details{color:#b8c7dc;font-size:14px;margin-top:12px}summary{cursor:pointer;font-weight:600}',
    'details li{margin:6px 0;overflow-wrap:anywhere}',
    '.empty{padding:35px;border:1px dashed #35516b;border-radius:14px;color:#a5b4cb}',
    'footer{margin-top:55px;color:#8293ad;font-size:12px}',
    '@media(max-width:620px){.stats{grid-template-columns:1fr 1fr}main{padding:30px 16px}}'
  ].join('\n');
  return '<!doctype html><html lang="en"><head><meta charset="utf-8">' +
    '<meta name="viewport" content="width=device-width,initial-scale=1">' +
    '<title>BreakMyApp Scan Report</title><style>' + css + '</style></head><body>' +
    '<main><div class="brand">◈ BREAKMYAPP / SCAN REPORT</div>' +
    '<h1>Your website, under the microscope.</h1>' +
    '<p class="subtitle">Target: <strong>' + escapeHtml(result.target) + '</strong></p>' +
    '<p class="muted">Chromium · ' + result.viewports.length +
    ' viewports · ' + (result.pagesScanned?.length ?? 1) + ' pages · ' +
    escapeHtml(result.finishedAt) + '</p>' +
    '<section class="stats" aria-label="Finding counts">' +
    '<div class="stat"><b>' + high + '</b><span>High severity</span></div>' +
    '<div class="stat"><b>' + medium + '</b><span>Medium severity</span></div>' +
    '<div class="stat"><b>' + low + '</b><span>Low severity</span></div></section>' +
    (result.pagesScanned && result.pagesScanned.length > 1
      ? '<details><summary>Scanned pages (' + result.pagesScanned.length +
        ')</summary><ol>' + result.pagesScanned.map(url =>
          '<li><code>' + escapeHtml(url) + '</code></li>'
        ).join('') + '</ol></details>'
      : '') +
    '<h2>Findings (' + result.findings.length + ')</h2>' + issues +
    '<footer>Local, offline-readable report · Generated by BreakMyApp v' +
    escapeHtml(result.toolVersion) +
    '. Automated checks cannot prove an application is bug-free. Treat screenshots as potentially sensitive.</footer>' +
    '</main></body></html>';
}

export async function writeReports(result: ScanResult, outputDir: string): Promise<void> {
  await mkdir(outputDir, { recursive: true });
  await Promise.all([
    writeFile(join(outputDir, 'report.json'), JSON.stringify(result, null, 2) + '\n', 'utf8'),
    writeFile(join(outputDir, 'index.html'), renderHtmlReport(result), 'utf8')
  ]);
}
