import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { Finding, ScanResult } from './types.js';

/** Only observed, deterministic checks are eligible for one-command reproductions. */
export type ReproKind = 'overflow' | 'runtime' | 'navigation' | 'resource' | 'accessibility';
export interface ReproPlan {
  kind: ReproKind;
  pageUrl: string;
  viewport: { width: number; height: number };
  expected: string | number;
  resourceUrl?: string;
  resourceType?: string;
}

/** Query strings, fragments and embedded credentials never go into generated scripts. */
export function safeReproUrl(value: string): string | null {
  try {
    const u = new URL(value);
    if ((u.protocol !== 'http:' && u.protocol !== 'https:') || u.username || u.password) return null;
    u.search = '';
    u.hash = '';
    return u.href;
  } catch { return null; }
}

/** Returns null for unsupported/uncertain checks; never claims to reproduce everything. */
export function planReproduction(f: Finding, fallback: string): ReproPlan | null {
  const pageUrl = safeReproUrl(f.pageUrl || fallback);
  if (!pageUrl || !Number.isInteger(f.viewport.width) || !Number.isInteger(f.viewport.height)) return null;
  const viewport = { width: f.viewport.width, height: f.viewport.height };
  if (f.ruleId === 'layout.horizontal-overflow') {
    return { kind: 'overflow', pageUrl, viewport, expected: 2 };
  }
  if (f.ruleId === 'runtime.uncaught-error' && f.description.length) {
    return { kind: 'runtime', pageUrl, viewport, expected: f.description.slice(0, 500) };
  }
  if (f.ruleId === 'navigation.http-error') {
    const match = /HTTP (4\d\d|5\d\d)/.exec(f.description);
    if (match) return { kind: 'navigation', pageUrl, viewport, expected: Number(match[1]) };
  }
  if (f.ruleId === 'resources.http-error') {
    const match = /^(image|script|stylesheet) at (https?:\/\/\S+) \(HTTP (4\d\d|5\d\d)\)$/.exec(f.description);
    if (match) {
      const resourceUrl = safeReproUrl(match[2]);
      if (resourceUrl) return { kind: 'resource', pageUrl, viewport, resourceUrl,
        resourceType: match[1], expected: Number(match[3]) };
    }
  }
  if (f.ruleId.startsWith('a11y.') && f.ruleId.length > 'a11y.'.length &&
      f.ruleId !== 'a11y.audit-failed') {
    return { kind: 'accessibility', pageUrl, viewport, expected: f.ruleId.slice(5) };
  }
  return null;
}

/**
 * Generated scripts use Playwright plus Node's native test runner, without eval,
 * copied HTML, generated selectors, or user-controlled JavaScript execution.
 */
export function generateReproScript(plan: ReproPlan): string {
  const url = JSON.stringify(plan.pageUrl);
  const width = plan.viewport.width;
  const height = plan.viewport.height;
  const expected = JSON.stringify(plan.expected);
  const body: Record<ReproKind, string> = {
    overflow: `const overflow = await page.evaluate(() => Math.max(document.documentElement.scrollWidth, document.body?.scrollWidth ?? 0) - window.innerWidth);\n    assert.ok(overflow > ${expected}, 'Expected observable horizontal overflow');`,
    runtime: `assert.ok(runtimeErrors.includes(${expected}), 'Expected observed uncaught JavaScript error');`,
    navigation: `assert.equal(response?.status(), ${expected}, 'Expected the observed HTTP status');`,
    resource: `assert.ok(resourceResponses.some(r => r.url === ${JSON.stringify(plan.resourceUrl)} && r.type === ${JSON.stringify(plan.resourceType)} && r.status === ${expected}), 'Expected static resource HTTP error');`,
    accessibility: `const AxeBuilder = (await import('@axe-core/playwright')).default;\n    const results = await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']).analyze();\n    assert.ok(results.violations.some(v => v.id === ${expected}), 'Expected observed axe accessibility rule violation');`
  };
  return `// Generated by BreakMyApp. Review before running against an authorized site.\n` +
    `// This verifies the observed condition, not necessarily a user-visible bug.\n` +
    `import test from 'node:test';\nimport assert from 'node:assert/strict';\n` +
    `import { chromium } from 'playwright';\n\n` +
    `test(${JSON.stringify('BreakMyApp ' + plan.kind + ' observation')}, async () => {\n` +
    `  const browser = await chromium.launch({headless:true});\n  try {\n` +
    `    const context = await browser.newContext({viewport:{width:${width},height:${height}}});\n` +
    `    const page = await context.newPage();\n` +
    `    await page.route('**/*', route => { if (route.request().isNavigationRequest() && new URL(route.request().url()).origin !== new URL(${url}).origin) return route.abort('blockedbyclient'); return route.continue(); });\n` +
    `    const runtimeErrors = [];\n    const resourceResponses = [];\n` +
    `    page.on('pageerror', e => runtimeErrors.push(e.message));\n` +
    `    page.on('response', r => { const u = new URL(r.url()); u.search=''; u.hash=''; u.username=''; u.password=''; resourceResponses.push({url:u.href,type:r.request().resourceType(),status:r.status()}); });\n` +
    `    const response = await page.goto(${url}, {waitUntil:'domcontentloaded',timeout:20000});\n` +
    `    await page.waitForTimeout(300);\n    ${body[plan.kind]}\n` +
    `  } finally { await browser.close(); }\n});\n`;
}

export async function writeReproductionPacks(result: ScanResult, outputDir: string): Promise<number> {
  const folder = join(outputDir, 'repros');
  const jobs: Array<Promise<void>> = [];
  let count = 0;
  const used = new Set<string>();
  for (const finding of result.findings) {
    if (count >= 100 || !/^[a-f0-9]{16}$/.test(finding.id)) continue;
    const plan = planReproduction(finding, result.target);
    if (!plan) continue;
    const path = 'repros/' + finding.id + '.test.mjs';
    if (used.has(path)) continue;
    used.add(path);
    if (!jobs.length) await mkdir(folder, { recursive: true });
    jobs.push(writeFile(join(folder, finding.id + '.test.mjs'), generateReproScript(plan), 'utf8'));
    finding.evidence = { ...finding.evidence, repro: path };
    count++;
  }
  await Promise.all(jobs);
  return count;
}
