const ALLOWED = new Set(['high','medium','low']);

export function parseReport(value) {
  const report = typeof value === 'string' ? JSON.parse(value) : value;
  if (!report || Array.isArray(report) || report.schemaVersion !== 1 || !Array.isArray(report.findings))
    throw Error('Expected a BreakMyApp report.json with schemaVersion 1.');
  if (report.findings.length > 50000) throw Error('Report exceeds 50,000 findings.');
  const findings = report.findings.map((f,i) => {
    if (!f || typeof f.ruleId !== 'string' || !ALLOWED.has(f.severity) ||
      !f.viewport || !Number.isFinite(f.viewport.width) || !Number.isFinite(f.viewport.height))
      throw Error('Invalid finding at index ' + i);
    return {...f, id:String(f.id ?? i), title:String(f.title ?? f.ruleId),
      description:String(f.description ?? ''), selector:String(f.selector ?? ''),
      confidence:f.confidence === 'confirmed' ? 'confirmed' : 'needs-review'};
  });
  return {...report, target:String(report.target ?? 'Unknown target'), findings};
}

export function identityOf(f) {
  let detail = f.selector || '';
  if (!detail && f.ruleId.startsWith('resources.'))
    detail = f.description.replace(/\s*\((?:HTTP \d{3}|net::[^)]*)\)\s*$/, '');
  if (!detail && f.ruleId.startsWith('runtime.')) detail = f.description;
  return JSON.stringify([f.ruleId, f.viewport.width, f.viewport.height, detail]);
}

export function compareReports(current, baseline = null) {
  const next = parseReport(current);
  const previous = baseline ? parseReport(baseline) : null;
  const old = new Map();
  for (const f of previous?.findings ?? []) {
    const key = identityOf(f);
    if (!old.has(key)) old.set(key, []);
    old.get(key).push(f);
  }
  const findings = next.findings.map(f => {
    const matches = old.get(identityOf(f)) ?? [];
    return {...f, change:previous ? (matches.shift() ? 'existing' : 'new') : 'uncompared'};
  });
  if (previous) for (const matches of old.values())
    for (const f of matches) findings.push({...f, change:'resolved'});
  return {findings, hasBaseline:!!previous, counts:{
    total:next.findings.length,
    high:next.findings.filter(f=>f.severity==='high').length,
    medium:next.findings.filter(f=>f.severity==='medium').length,
    low:next.findings.filter(f=>f.severity==='low').length,
    new:findings.filter(f=>f.change==='new').length,
    existing:findings.filter(f=>f.change==='existing').length,
    resolved:findings.filter(f=>f.change==='resolved').length
  }};
}

export function filterFindings(findings, {query='',severity='all',change='all'}={}) {
  const q=String(query).toLowerCase().trim();
  return findings.filter(f=>(severity==='all'||f.severity===severity)&&
    (change==='all'||f.change===change)&&
    (!q||[f.title,f.ruleId,f.description,f.selector,f.viewport.width+'x'+f.viewport.height]
      .some(v=>String(v??'').toLowerCase().includes(q))));
}

export function makeIssue(f,target) {
  return '# '+f.title+'\n\nRule: '+f.ruleId+
    '\nSeverity: '+f.severity+'\nConfidence: '+f.confidence+
    '\nViewport: '+f.viewport.width+'x'+f.viewport.height+
    '\nTarget: '+target+'\n\n'+f.description+
    (f.selector?'\n\nElement: '+f.selector:'')+
    (f.evidence?.detail?'\n\nEvidence: '+f.evidence.detail:'')+
    '\n\nGenerated by BreakMyApp Studio. Verify before filing.\n';
}
